import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { Poppins } from "next/font/google";
import { ReactQueryProviders } from "@/feature/reactQueryProviders";
import { Toaster } from "sonner";

const font = Poppins({
  subsets: ["latin"],
  weight: ["600"],
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProviders>
      <html lang="en">
        <body className={`${font.className} ${geistMono.variable} antialiased`}>
          {children}
          <Toaster />
        </body>
      </html>
    </ReactQueryProviders>
  );
}
